# Cloud Run 部署配置
# 用于部署 iFood 抓取 API 到 Cloud Run

# 部署命令示例:
# gcloud run deploy ifood-scraper \
#   --image gcr.io/YOUR_PROJECT_ID/ifood-scraper \
#   --platform managed \
#   --region us-central1 \
#   --allow-unauthenticated \
#   --memory 4Gi \
#   --cpu 2 \
#   --timeout 900 \
#   --max-instances 10 \
#   --min-instances 0 \
#   --concurrency 1 \
#   --set-env-vars-file cloud_run_config.yaml

# 环境变量配置
API_TOKEN: "4a27e60b5b0464a72ae12ba3731e077cc5951b40937999e78d06fb5325524800"
USE_GCP_NATURAL_IP_ROTATION: "true"
LOG_LEVEL: "INFO"

# 可选：云代理配置（如果不想使用GCP自然IP轮换）
# CLOUD_PROXY_USERNAME: "your_proxy_username"
# CLOUD_PROXY_PASSWORD: "your_proxy_password" 
# CLOUD_PROXY_HOST: "proxy.provider.com"
# CLOUD_PROXY_PORT: "1080"

# 代理轮换策略（当使用云代理时）
# PROXY_ROTATION_STRATEGY: "random"

# Cloud Run 特定配置
PORT: "8080" 